In [42]:
import pandas as pd
import pymongo

df=pd.read_csv('C:/yeshwanth/github_repos/MLOPS-MOVIE-RECOMMENDATION-SYSTEM/notebook/df_movies.csv')
df.head()

,id,title,overview,genres,cast,director,keywords,rating,vote_count,release_date,imdb_rating,imdb_votes,poster_url,backdrop_url
0,533533,TRON: Ares,A highly sophisticated Program called Ares is ...,"['Science Fiction', 'Adventure', 'Action']","['Jared Leto', 'Greta Lee', 'Evan Peters', 'Gi...",Joachim Rønning,"['artificial intelligence (a.i.)', 'computer p...",6.548,656,2025-10-08,NaN,NaN,https://image.tmdb.org/t/p/w500/chpWmskl3aKm1a...,https://image.tmdb.org/t/p/w500/min9ZUDZbiguTi...
1,1180831,Troll 2,When a dangerous new troll unleashes devastati...,"['Action', 'Fantasy', 'Thriller']","['Ine Marie Wilmann', 'Kim S. Falck-Jørgensen'...",Roar Uthaug,"['mythical creature', 'sequel', 'troll', 'kaij...",6.800,218,2025-11-30,NaN,NaN,https://image.tmdb.org/t/p/w500/p6xAExLNFbHcLf...,https://image.tmdb.org/t/p/w500/lZYMXx74pWmbj5...
2,1083637,Kantara - A Legend: Chapter 1,"During the Kadamba reign, King Vijayendra, the...","['Action', 'Drama', 'Fantasy']","['Rishab Shetty', 'Rukmini Vasanth', 'Jayaram'...",Rishab Shetty,[],6.957,46,2025-10-01,NaN,NaN,https://image.tmdb.org/t/p/w500/zBvw25afDn93em...,https://image.tmdb.org/t/p/w500/w57nxiBIODAYHL...
3,23527,First Squad: The Moment of Truth,Set during the opening days of World War II on...,"['Fantasy', 'Animation', 'Action', 'Science Fi...","['Sergei Aisman', 'Michael Beskorovainy', 'Ele...",Yoshiharu Ashino,"['supernatural', 'super soldier', 'russian army']",6.200,129,2009-05-13,NaN,NaN,https://image.tmdb.org/t/p/w500/hBj1aTnGf4564K...,https://image.tmdb.org/t/p/w500/3k1PKmzNEosWFa...
4,1448560,Wildcat,An ex-black ops team reunite to pull off a des...,"['Action', 'Thriller', 'Crime']","['Kate Beckinsale', 'Lewis Tan', 'Alice Krige'...",James Nunn,"['playful', 'embarrassed']",5.838,34,2025-11-19,NaN,NaN,https://image.tmdb.org/t/p/w500/h893ImjM6Fsv5D...,https://image.tmdb.org/t/p/w500/pAyImoslSnpMgj...

In [43]:

#df should be converted into dictionary before pushing into mongodb
data=df.to_dict(orient='records')
data

[{'id': 533533,
  'title': 'TRON: Ares',
  'overview': "A highly sophisticated Program called Ares is sent from the digital world into the real world on a dangerous mission, marking humankind's first encounter with A.I. beings.",
  'genres': "['Science Fiction', 'Adventure', 'Action']",
  'cast': "['Jared Leto', 'Greta Lee', 'Evan Peters', 'Gillian Anderson', 'Jodie Turner-Smith', 'Jeff Bridges', 'Hasan Minhaj', 'Arturo Castro', 'Cameron Monaghan', 'Sarah Desjardins']",
  'director': 'Joachim Rønning',
  'keywords': "['artificial intelligence (a.i.)', 'computer program', 'simulation', 'computer simulation', 'sequel', 'business rivalry', 'real world', 'digital world']",
  'rating': 6.548,
  'vote_count': 656,
  'release_date': '2025-10-08',
  'imdb_rating': nan,
  'imdb_votes': nan,
  'poster_url': 'https://image.tmdb.org/t/p/w500/chpWmskl3aKm1aTZqUHRCtviwPy.jpg',
  'backdrop_url': 'https://image.tmdb.org/t/p/w500/min9ZUDZbiguTiQ7yz1Hbqk78HT.jpg'},
 {'id': 1180831,
  'title': 'Troll 2',
  'overview': 'When a dangerous new troll unleashes devastation across their homeland, Nora, Andreas and Major Kris embark on their most perilous mission yet.',
  'genres': "['Action', 'Fantasy', 'Thriller']",
  'cast': "['Ine Marie Wilmann', 'Kim S. Falck-Jørgensen', 'Mads Sjøgård Pettersen', 'Sara Khorami', 'Karoline Viktoria Sletteng Garvang', 'Anne Krigsvoll', 'Duc Mai-The', 'Jon Ketil Johnsen', 'Ola G. Furuseth', 'Yusuf Toosh Ibra']",
  'director': 'Roar Uthaug',
  'keywords': "['mythical creature', 'sequel', 'troll', 'kaiju', 'oslo, norway', 'angry', 'monster movie', 'norwegian folklore', 'action thriller']",
  'rating': 6.8,
  'vote_count': 218,
  'release_date': '2025-11-30',
  'imdb_rating': nan,
  'imdb_votes': nan,
  'poster_url': 'https://image.tmdb.org/t/p/w500/p6xAExLNFbHcLfvSuvLPoM8aqZU.jpg',
  'backdrop_url': 'https://image.tmdb.org/t/p/w500/lZYMXx74pWmbj5Q5jp1QaMvmuuR.jpg'},
 {'id': 1083637,
  'title': 'Kantara - A Legend: Chapter 1',
  'overview': 'During the Kadamba reign, King Vijayendra, the ruler of the fictional feudatory land of Bangra, meets his final fate while venturing into the mystical forest of Kantara. Witnessing this, his son Rajashekara seals the borders of their realm. Later, Prince Kulashekara reopens them through a brutal massacre. The protagonist, Berme, in search of prosperity, crosses the divide and ignites a conflict of faith, power, and destiny between the Kingdom and Nature.',
  'genres': "['Action', 'Drama', 'Fantasy']",
  'cast': "['Rishab Shetty', 'Rukmini Vasanth', 'Jayaram', 'Gulshan Devaiah', 'Ramitha Shailendra', 'Pramod Shetty', 'Naveen D. Padil', 'Rakesh Poojari', 'Prakash Thuminad', 'Deepak Rai Panaje']",
  'director': 'Rishab Shetty',
  'keywords': '[]',
  'rating': 6.957,
  'vote_count': 46,
  'release_date': '2025-10-01',
  'imdb_rating': nan,
  'imdb_votes': nan,
  'poster_url': 'https://image.tmdb.org/t/p/w500/zBvw25afDn93embB8L7FzvTT2xq.jpg',
  'backdrop_url': 'https://image.tmdb.org/t/p/w500/w57nxiBIODAYHLRs1xmrCY9zEFe.jpg'},
 {'id': 23527,
  'title': 'First Squad: The Moment of Truth',
  'overview': 'Set during the opening days of World War II on the Eastern Front. Its main cast are a group of Soviet teenagers with extraordinary abilities; the teenagers have been drafted to form a special unit to fight the invading German army. They are opposed by a Schutzstaffel officer who is attempting to raise from the dead a supernatural army of crusaders from the 12th-century Order of the Sacred Cross.',
  'genres': "['Fantasy', 'Animation', 'Action', 'Science Fiction']",
  'cast': "['Sergei Aisman', 'Michael Beskorovainy', 'Elena Chebaturkina', 'Damir Eldarov', 'Olga Golovanova', 'Alexander Gruzdev', 'Artem Kipnis', 'Rudolf Pankov', 'Mikhail Tikhonov', 'Nikita Prozorovsky']",
  'director': 'Yoshiharu Ashino',
  'keywords': "['supernatural', 'super soldier', 'russian army']",
  'rating': 6.2,
  'vote_count': 129,
  'release_date': '2009-05-13',
  'imdb_rating': nan,
  'imdb_votes': nan,
  'poster_url': 'https://image.tmdb.org/t/p/w500/hBj1aTnGf4564Klv9yIbSuB7Y8w.jpg',
  'backdrop_url': 'https://image.tmdb.org/t/p/w500/3k1PKmzNEosWFaOR1yC9ZKIYqmm.jpg'},
 {'id': 1448560,
  'title': 'Wildcat',
  'overview': 'An ex-black ops team reunite to pull off a desperate heist in order to save the life of their leader’s eight-year-old daughter.',
  'genres': "['Action', 'Thriller', 'Crime']",
  'cast': "['Kate Beckinsale', 'Lewis Tan', 'Alice Krige', 'Charles Dance', 'Rasmus Hardiker', 'Mathilde Warnier', 'Bailey Patrick', 'Tom Bennett', 'Matt Willis', 'Roxy Striar']",
  'director': 'James Nunn',
  'keywords': "['playful', 'embarrassed']",
  'rating': 5.838,
  'vote_count': 34,
  'release_date': '2025-11-19',
  'imdb_rating': nan,
  'imdb_votes': nan,
  'poster_url': 'https://image.tmdb.org/t/p/w500/h893ImjM6Fsv5DFhKJdlZFZIJno.jpg',
  'backdrop_url': 'https://image.tmdb.org/t/p/w500/pAyImoslSnpMgjRwhaS5ZEdl8UI.jpg'},
 {'id': 1033462,
  'title': 'Bureau 749',
  'overview': 'A traumatized young man with physical abnormalities is forced to join a mysterious bureau to confront a disaster spreading across the earth caused by an unknown creature. He embarks on an adventure uncovering mysteries about his life.',
  'genres': "['Action', 'Adventure', 'Science Fiction']",
  'cast': "['Karry Wang', 'Miao Miao', 'Ryan Zheng', 'Ren Min', 'Xin Baiqing', 'Jerry Lee', 'Ning Chang', 'Yang Haoyu', 'Yu Kailei', 'Li Meng']",
  'director': 'Lu Chuan',
  'keywords': "['joyful', 'mezcla documental y ficción']",
  'rating': 6.1,
  'vote_count': 54,
  'release_date': '2024-10-01',
  'imdb_rating': nan,
  'imdb_votes': nan,
  'poster_url': 'https://image.tmdb.org/t/p/w500/flykCMw22y6yv8vKnBjmsW3pneo.jpg',
  'backdrop_url': 'https://image.tmdb.org/t/p/w500/lf8IZ86ajGpgbuyHCZrXUeAMmvy.jpg'},
 {'id': 1242898,
  'title': 'Predator: Badlands',
  'overview': 'Cast out from his clan, a young Predator finds an unlikely ally in a damaged android and embarks on a treacherous journey in search of the ultimate adversary.',
  'genres': "['Action', 'Science Fiction', 'Adventure']",
  'cast': "['Elle Fanning', 'Dimitrius Schuster-Koloamatangi', 'Ravi Narayan', 'Michael Homick', 'Stefan Grube', 'Reuben De Jong', 'Cameron Brown', 'Alison Wright', 'Matt Duffer', 'Ross Duffer']",
  'director': 'Dan Trachtenberg',
  'keywords': "['survival', 'outcast', 'alien planet', 'thoughtful', 'team up', 'negative', 'arrogant', 'condescending', 'farcical', 'ridiculous']",
  'rating': 7.4,
  'vote_count': 585,
  'release_date': '2025-11-05',
  'imdb_rating': nan,
  'imdb_votes': nan,
  'poster_url': 'https://image.tmdb.org/t/p/w500/pHpq9yNUIo6aDoCXEBzjSolywgz.jpg',
  'backdrop_url': 'https://image.tmdb.org/t/p/w500/ebyxeBh56QNXxSJgTnmz7fXAlwk.jpg'},
 {'id': 1419406,
  'title': "The Shadow's Edge",
  'overview': 'Macau Police brings the tracking expert police officer out of retirement to help catch a dangerous group of professional thieves.',
  'genres': "['Action', 'Crime', 'Thriller']",
  'cast': "['Jackie Chan', 'Zhang Zifeng', 'Tony Leung Ka-fai', 'Ci Sha', 'Jun', 'Zhou Zhengjie', 'Wang Ziyi', 'Lang Yueting', 'Li Zhekun', 'Zac Wang']",
  'director': 'Larry Yang',
  'keywords': '[]',
  'rating': 6.503,
  'vote_count': 150,
  'release_date': '2025-08-16',
  'imdb_rating': nan,
  'imdb_votes': nan,
  'poster_url': 'https://image.tmdb.org/t/p/w500/e0RU6KpdnrqFxDKlI3NOqN8nHL6.jpg',
  'backdrop_url': 'https://image.tmdb.org/t/p/w500/4BtL2vvEufDXDP4u6xQjjQ1Y2aT.jpg'},
 {'id': 1218925,
  'title': 'Chainsaw Man - The Movie: Reze Arc',
  'overview': "In a brutal war between devils, hunters, and secret enemies, a mysterious girl named Reze has stepped into Denji's world, and he faces his deadliest battle yet, fueled by love in a world where survival knows no rules.",
  'genres': "['Animation', 'Action', 'Romance', 'Fantasy']",
  'cast': "['Kikunosuke Toya', 'Reina Ueda', 'Tomori Kusunoki', 'Shogo Sakata', 'Maaya Uchida', 'Natsuki Hanae', 'Karin Takahashi', 'Fairouz Ai', 'Yuuya Uchida', 'Shiori Izawa']",
  'director': 'Tatsuya Yoshihara',
  'keywords': "['regret', 'fight', 'identity', 'supernatural', 'manipulation', 'secret organization', 'gore', 'sequel', 'loneliness', 'chainsaw', 'based on manga', 'demon', 'adult animation', 'tragic romance', 'shocking', 'shounen', 'anime', 'complex', 'sentimental', 'intense', 'adoring']",
  'rating': 7.89,
  'vote_count': 259,
  'release_date': '2025-09-19',
  'imdb_rating': nan,
  'imdb_votes': nan,
  'poster_url': 'https://image.tmdb.org/t/p/w500/pHyxb2RV5wLlboAwm9ZJ9qTVEDw.jpg',
  'backdrop_url': 'https://image.tmdb.org/t/p/w500/kfXgo2rMF1A19celCwLyQ4Xwpf8.jpg'},
 {'id': 949709,
  'title': 'High Forces',
  'overview': '"Anyone? There is ......" A mysterious message from Gao Haojun comes from ten thousand meters in the air. A five-star A380 ultra-luxury airliner was hijacked on its international maiden voyage, and international security expert Gao Haojun stood up to a group of thugs, his daughter Xiaojun was trapped in the cabin, and Mike, the leader of the hijackers, threatened the lives of more than 800 people in the plane as a bargaining chip, and Xiaojun\'s mother, Fu Yuan, was also in danger. ...... Will the passengers on board be able to land safely and how should this crisis be resolved?',
  'genres': "['Action', 'Crime']",
  'cast': "['Andy Lau', 'Zhang Zifeng', 'Qu Chuxiao', 'Liu Tao', 'Guo Xiaodong', 'Jiang Mengjie', 'David Wang', 'Jiang Chao', 'Wang Longzheng', 'Zhang Yang']",
  'director': 'Oxide Pang Chun',
  'keywords': "['airplane', 'hijacking', 'airplane hijacking', 'disaster']",
  'rating': 5.889,
  'vote_count': 27,
  'release_date': '2024-09-29',
  'imdb_rating': nan,
  'imdb_votes': nan,
  'poster_url': 'https://image.tmdb.org/t/p/w500/v8ySgr4CE45SrrIt4PqqYc1diW6.jpg',
  'backdrop_url': 'https://image.tmdb.org/t/p/w500/8lqfrOBQ2EcY7znD3LxTYcvlh25.jpg'},
 {'id': 1363123,
  'title': 'The Family Plan 2',
  'overview': "Now that Dan's assassin days are behind him, all he wants for Christmas is quality time with his kids. But when he learns his daughter has her own plans, he books a family trip to London—putting them all in the crosshairs of an unexpected enemy.",
  'genres': "['Action', 'Comedy']",
  'cast': "['Mark Wahlberg', 'Michelle Monaghan', 'Kit Harington', 'Zoe Colletti', 'Van Crosby', 'Theodore Lindsey', 'Peter Lindsey', 'Reda Elazouar', 'Sidse Babett Knudsen', 'Sanjeev Bhaskar']",
  'director': 'Simon Cellan Jones',
  'keywords': "['europe vacation']",
  'rating': 6.661,
  'vote_count': 326,
  'release_date': '2025-11-11',
  'imdb_rating': nan,
  'imdb_votes': nan,
  'poster_url': 'https://image.tmdb.org/t/p/w500/semFxuYx6HcrkZzslgAkBqfJvZk.jpg',
  'backdrop_url': 'https://image.tmdb.org/t/p/w500/7nAVXGHHtaNcdsqvDXmY6R9N0fG.jpg'},
 {'id': 1309012,
  'title': 'Altered',
  'overview': 'In an alternate present, genetically enhanced humans dominate society. Outcasts Leon and Chloe fight for justice against corrupt politicians exploiting genetic disparity, risking everything to challenge the oppressive system.',
  'genres': "['Science Fiction', 'Action']",
  'cast': "['Tom Felton', 'Aggy K. Adams', 'Elizaveta Bugulova', 'Igor Jijikine', 'Richard Brake', 'Aleksey Filimonov', 'Daniyar Alshinov', 'Atamura Mussakhanov', 'Linda Nigmatulina', 'Yelzhas Rakhim']",
  'director': 'Timo Vuorensola',
  'keywords': '[]',
  'rating': 6.3,
  'vote_count': 58,
  'release_date': '2025-09-18',
  'imdb_rating': nan,
  'imdb_votes': nan,
  'poster_url': 'https://image.tmdb.org/t/p/w500/6QlAcGRaUrgHcZ4WTBh5lsPnzKx.jpg',
  'backdrop_url': 'https://image.tmdb.org/t/p/w500/q9bvjUkpKltPE0S9oxci2pmD1Zx.jpg'},
 {'id': 1539104,
  'title': 'JUJUTSU KAISEN: Execution -Shibuya Incident x The Culling Game Begins-',
  'overview': "A veil abruptly descends over the busy Shibuya area amid the bustling Halloween crowds, trapping countless civilians inside. Satoru Gojo, the strongest jujutsu sorcerer, steps into the chaos. But lying in wait are curse users and spirits scheming to seal him away. Yuji Itadori, accompanied by his classmates and other top-tier jujutsu sorcerers, enters the fray in an unprecedented clash of curses — the Shibuya Incident. In the aftermath, ten colonies across Japan are transformed into dens of curses in a plan orchestrated by Noritoshi Kamo. As the deadly Culling Game starts, Special Grade sorcerer Yuta Okkotsu is assigned to carry out Yuji's execution for his perceived crimes. A compilation movie of Shibuya Incident including the first two episodes of the Culling Games arc.",
  'genres': "['Animation', 'Action']",
  'cast': "['Junya Enoki', 'Megumi Ogata', 'Koji Yusa', 'Daisuke Namikawa', 'Yuma Uchida', 'Asami Seto', 'Kenjiro Tsuda', 'Subaru Kimura', 'Yuichi Nakamura', 'Takahiro Sakurai']",
  'director': 'Shota Goshozono',
  'keywords': "['compilation', 'based on manga', 'edited from tv series', 'shounen', 'anime']",
  'rating': 5.38,
  'vote_count': 54,
  'release_date': '2025-11-07',
  'imdb_rating': nan,
  'imdb_votes': nan,
  'poster_url': 'https://image.tmdb.org/t/p/w500/tc7RrVW5FGvyO2tsgW6LIN1esHI.jpg',
  'backdrop_url': 'https://image.tmdb.org/t/p/w500/eMBYlgFTHfZaTz96eJxlkeMsKo9.jpg'},
 {'id': 1311031,
  'title': 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
  'overview': 'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.',
  'genres': "['Animation', 'Action', 'Fantasy']",
  'cast': "['Natsuki Hanae', 'Hiro Shimono', 'Takahiro Sakurai', 'Akira Ishida', 'Yoshitsugu Matsuoka', 'Toshihiko Seki', 'Reina Ueda', 'Nobuhiko Okamoto', 'Katsuyuki Konishi', 'Akari Kito']",
  'director': 'Haruo Sotozaki',
  'keywords': "['supernatural', 'affectation', 'sequel', 'based on manga', 'demon', 'shounen', 'anime', 'brother sister relationship', 'taisho period', 'admiring', 'amused']",
  'rating': 7.613,
  'vote_count': 591,
  'release_date': '2025-07-18',
  'imdb_rating': nan,
  'imdb_votes': nan,
  'poster_url': 'https://image.tmdb.org/t/p/w500/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg',
  'backdrop_url': 'https://image.tmdb.org/t/p/w500/1RgPyOhN4DRs225BGTlHJqCudII.jpg'},
 {'id': 1196573,
  'title': 'She Rides Shotgun',
  'overview': 'Newly released from prison and marked for death by unrelenting enemies, Nate must now protect his estranged 11-year-old daughter, Polly, at all costs. With scant resources and no one to trust, Nate and Polly forge a bond under fire as he shows her how to fight and survive—and she teaches him the true meaning of unconditional love.',
  'genres': "['Action', 'Thriller', 'Crime']",
  'cast': '[\'Taron Egerton\', \'Ana Sophia Heger\', "Odessa A\'zion", \'John Carroll Lynch\', \'David Lyons\', \'Rob Yang\', \'Keith Jardine\', \'Jamie Bernadette\', \'Goldie Tom\', \'Kiko Sanchez\']',
  'director': 'Nick Rowland',
  'keywords': "['based on novel or book', 'on the run', 'aggressive', 'estranged daughter', 'father daughter relationship', 'anxious', 'prison gang', 'father and daughter', 'young girl', 'crime', 'criminal father', 'brisk', 'forceful', 'tragic', 'urgent', 'loss of a parent']",
  'rating': 7.083,
  'vote_count': 138,
  'release_date': '2025-07-31',
  'imdb_rating': nan,
  'imdb_votes': nan,
  'poster_url': 'https://image.tmdb.org/t/p/w500/nvqW8mOm818QDio3GKKmPLK8kXj.jpg',
  'backdrop_url': 'https://image.tmdb.org/t/p/w500/ytCi1wg6YHpYcFRWCO2jpzN31Kf.jpg'},
 {'id': 1116465,
  'title': 'A Legend',
  'overview': 'An archeologist noticed that the texture of the relics discovered during the excavation of a glacier closely resembled a jade pendant seen in one of his dreams. He and his team then embark on an expedition into the depths of the glacier.',
  'genres': "['Action', 'Adventure', 'Fantasy']",
  'cast': "['Jackie Chan', 'Zhang Yixing', 'Gulnezer Bextiyar', 'Aarif Rahman', 'Jerry Lee', 'Peng Xiaoran', 'Shawn Dou', 'Zheng Yecheng', 'Ma Yuan', 'Ray Lui']",
  'director': 'Stanley Tong Gwai-Lai',
  'keywords': "['burlesque', 'inspirational', 'admiring', 'amused', 'awestruck', 'hopeful']",
  'rating': 6.879,
  'vote_count': 124,
  'release_date': '2024-07-05',
  'imdb_rating': nan,
  'imdb_votes': nan,
  'poster_url': 'https://image.tmdb.org/t/p/w500/qbImUt1d3itXcB81BCItPZlfbyr.jpg',
  'backdrop_url': 'https://image.tmdb.org/t/p/w500/7FDVhmCur4LMOfnXMteiSCtsdOb.jpg'},
 {'id': 1054867,
  'title': 'One Battle After Another',
  'overview': 'Washed-up revolutionary Bob exists in a state of stoned paranoia, surviving off-grid with his spirited, self-reliant daughter, Willa. When his evil nemesis resurfaces after 16 years and she goes missing, the former radical scrambles to find her, father and daughter both battling the consequences of his past.',
  'genres': "['Thriller', 'Crime', 'Action']",
  'cast': "['Leonardo DiCaprio', 'Sean Penn', 'Chase Infiniti', 'Benicio del Toro', 'Regina Hall', 'Teyana Taylor', 'Wood Harris', 'Tony Goldwyn', 'D.W. Moffett', 'Paul Grimstad']",
  'director': 'Paul Thomas Anderson',
  'keywords': "['rebellion', 'based on novel or book', 'resistance', 'usa–mexico border', 'riot', 'interracial relationship', 'on the run', 'xenophobia', 'aftercreditsstinger', 'missing daughter', 'white supremacy', 'anti-fascism', 'father daughter relationship', 'revolutionaries', 'african american', 'anti-racism', 'immigration detention center']",
  'rating': 7.5,
  'vote_count': 1809,
  'release_date': '2025-09-23',
  'imdb_rating': nan,
  'imdb_votes': nan,
  'poster_url': 'https://image.tmdb.org/t/p/w500/m1jFoahEbeQXtx4zArT2FKdbNIj.jpg',
  'backdrop_url': 'https://image.tmdb.org/t/p/w500/zpEWFNqoN8Qg1SzMMHmaGyOBTdW.jpg'},
 {'id': 1208561,
  'title': 'Art of Eight Limbs',
  'overview': 'Four canisters of deadly VX nerve gas have fallen into the hands of an international arms dealer in Myanmar. A CIA recruit delivers a high-tech detection device to an agent already on the ground.',
  'genres': "['Action', 'Thriller']",
  'cast': "['Ludi Lin', 'Grace Vorananth', 'Sahajak Boonthanakit', 'Nicholas Hammond', 'Vithaya Pansringarm', 'Ron Smoorenburg', 'Tofan Pirani', 'Andrey Kasushkin', 'Maverick Kamuela Kang Jr.', 'Jaroslav Shvets']",
  'director': 'Robert Grasmere',
  'keywords': "['martial arts', 'undercover agent', 'action thriller']",
  'rating': 6.4,
  'vote_count': 37,
  'release_date': '2024-08-16',
  'imdb_rating': nan,
  'imdb_votes': nan,
  'poster_url': 'https://image.tmdb.org/t/p/w500/tZRypLd2SU3Eeqg5tD5cwkk5CdL.jpg',
  'backdrop_url': 'https://image.tmdb.org/t/p/w500/cVzAhirOhKh91AB1TFcGn0Rh5c3.jpg'},
 {'id': 575265,
  'title': 'Mission: Impossible - The Final Reckoning',
  'overview': "Ethan Hunt and team continue their search for the terrifying AI known as the Entity — which has infiltrated intelligence networks all over the globe — with the world's governments and a mysterious ghost from Hunt's past on their trail. Joined by new allies and armed with the means to shut the Entity down for good, Hunt is in a race against time to prevent the world as we know it from changing forever.",
  'genres': "['Action', 'Thriller']",
  'cast': "['Tom Cruise', 'Hayley Atwell', 'Ving Rhames', 'Simon Pegg', 'Esai Morales', 'Pom Klementieff', 'Henry Czerny', 'Holt McCallany', 'Janet McTeer', 'Nick Offerman']",
  'director': 'Christopher McQuarrie',
  'keywords': "['mask', 'artificial intelligence (a.i.)', 'diving', 'submarine', 'espionage', 'spy', 'nuclear missile', 'fake identity', 'secret agent', 'stunt', 'sequel', 'secret government organization', 'infiltration', 'terrorist plot', 'fictional government agency', 'misinformation', 'government agency', 'based on tv series', 'suspenseful']",
  'rating': 7.259,
  'vote_count': 2160,
  'release_date': '2025-05-17',
  'imdb_rating': nan,
  'imdb_votes': nan,
  'poster_url': 'https://image.tmdb.org/t/p/w500/z53D72EAOxGRqdr7KXXWp9dJiDe.jpg',
  'backdrop_url': 'https://image.tmdb.org/t/p/w500/xPNDRM50a58uvv1il2GVZrtWjkZ.jpg'},
 {'id': 617126,
  'title': 'The Fantastic 4: First Steps',

In [44]:
df.shape

(1635, 14)

In [ ]:
DB_NAME = "movie_recommender"
COLLECTION_NAME = "movies_metadata"

CONNECTION_URL='mongodb+srv://shivakeshava1809_db_user:MAnT4yAbptYYjrvg@cluster0.3ahti1w.mongodb.net/?appName=Cluster0'

In [46]:
client=pymongo.MongoClient(CONNECTION_URL)
data_base=client[DB_NAME]
collection=data_base[COLLECTION_NAME]

In [47]:
from pymongo import MongoClient

client = MongoClient(CONNECTION_URL, serverSelectionTimeoutMS=5000)

print(client.admin.command("ping"))

{'ok': 1}

In [48]:
# Uploading data to MongoDB
rec=collection.insert_many(data)

In [49]:
df.shape

(1635, 14)

In [50]:
df.isnull().sum()

id                 0
title              0
overview           0
genres             0
cast               0
director           0
keywords           0
rating             0
vote_count         0
release_date       0
imdb_rating     1627
imdb_votes      1626
poster_url         0
backdrop_url      13
dtype: int64

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1635 entries, 0 to 1634
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1635 non-null   int64
 1   title         1635 non-null   object
 2   overview      1635 non-null   object
 3   genres        1635 non-null   object
 4   cast          1635 non-null   object
 5   director      1635 non-null   object
 6   keywords      1635 non-null   object
 7   rating        1635 non-null   float64
 8   vote_count    1635 non-null   int64
 9   release_date  1635 non-null   object
 10  imdb_rating   8 non-null      float64
 11  imdb_votes    9 non-null      object
 12  poster_url    1635 non-null   object
 13  backdrop_url  1622 non-null   object
dtypes: float64(2), int64(2), object(10)
memory usage: 179.0+ KB

In [52]:
#dropping the columns fo imbd_rating and imbd_votes
df = df.drop(columns=["imdb_rating", "imdb_votes"], errors="ignore")

In [53]:
df.isnull().sum()

id               0
title            0
overview         0
genres           0
cast             0
director         0
keywords         0
rating           0
vote_count       0
release_date     0
poster_url       0
backdrop_url    13
dtype: int64

In [54]:
df.describe()

                 id       rating    vote_count
count  1.635000e+03  1635.000000   1635.000000
mean   4.234760e+05     6.797229   3611.424465
std    4.662535e+05     0.920127   6113.958300
min    1.100000e+01     3.115000     11.000000
25%    1.480300e+04     6.229500     64.000000
50%    2.420950e+05     6.899000    527.000000
75%    7.877230e+05     7.452000   4278.000000
max    1.589891e+06     9.316000  38360.000000

In [55]:
# Remove rows where 'keywords' column has missing values
df = df.dropna(subset=['keywords'])

In [56]:
df.isnull().sum()

id               0
title            0
overview         0
genres           0
cast             0
director         0
keywords         0
rating           0
vote_count       0
release_date     0
poster_url       0
backdrop_url    13
dtype: int64

In [57]:
df.shape

(1635, 12)